use_frameworks!

platform :ios, '9.0'

target 'XBCocoaLibrary_Example' do
  pod 'XBCocoaLibrary', :path => '../'

  target 'XBCocoaLibrary_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
